export * from '@datas/pages/config/_types';
export * from '@datas/pages/config/cards';
export * from '@datas/pages/config/banners';
export * from '@datas/pages/config/charts';
export * from '@datas/pages/config/autocomplete';
export * from '@datas/pages/config/button';
export * from '@datas/pages/config/checkbox';
export * from '@datas/pages/config/radio';
export * from '@datas/pages/config/datepicker';